# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Api.Account do
  @moduledoc """
  API calls for all endpoints tagged `Account`.
  """

  alias OddittApiClient.Connection
  import OddittApiClient.RequestBuilder

  @doc """
  List own API keys

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthListApiKeysResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_api_keys_get(Tesla.Env.client, keyword()) :: {:ok, OddittApiClient.Model.AuthListApiKeysResponse.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_api_keys_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/account/api-keys")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OddittApiClient.Model.AuthListApiKeysResponse},
      {401, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  Deactivate an API key

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `key_code` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_api_keys_key_code_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, OddittApiClient.Model.V1AccountApiKeysKeyCodeDelete409Response.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_api_keys_key_code_delete(connection, key_code, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/v1/account/api-keys/#{key_code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {401, OddittApiClient.Model.AuthErrorResponse},
      {409, OddittApiClient.Model.V1AccountApiKeysKeyCodeDelete409Response}
    ])
  end

  @doc """
  Create a new API key

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `auth_create_api_key_request` (AuthCreateApiKeyRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthCreateApiKeyResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_api_keys_post(Tesla.Env.client, OddittApiClient.Model.AuthCreateApiKeyRequest.t, keyword()) :: {:ok, OddittApiClient.Model.AuthCreateApiKeyResponse.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_api_keys_post(connection, auth_create_api_key_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/account/api-keys")
      |> add_param(:body, :body, auth_create_api_key_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, OddittApiClient.Model.AuthCreateApiKeyResponse},
      {400, OddittApiClient.Model.AuthErrorResponse},
      {401, OddittApiClient.Model.AuthErrorResponse},
      {422, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  Delete the check endpoint

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_check_endpoint_delete(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, OddittApiClient.Model.V1AccountApiKeysKeyCodeDelete409Response.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_check_endpoint_delete(connection, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/v1/account/check-endpoint")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {401, OddittApiClient.Model.AuthErrorResponse},
      {409, OddittApiClient.Model.V1AccountApiKeysKeyCodeDelete409Response}
    ])
  end

  @doc """
  Get the configured check endpoint
  Returns the URL, method and bearer token preview for the check endpoint used by flow quoting. The full bearer token is never returned.

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthCheckEndpointResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_check_endpoint_get(Tesla.Env.client, keyword()) :: {:ok, OddittApiClient.Model.AuthCheckEndpointResponse.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_check_endpoint_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/account/check-endpoint")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OddittApiClient.Model.AuthCheckEndpointResponse},
      {401, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  Set the check endpoint (upsert)
  Stores or updates the URL, method and bearer token used to quote flows against the client's own service. A single configuration exists per client.

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `auth_set_check_endpoint_request` (AuthSetCheckEndpointRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthCheckEndpointResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_check_endpoint_post(Tesla.Env.client, OddittApiClient.Model.AuthSetCheckEndpointRequest.t, keyword()) :: {:ok, OddittApiClient.Model.AuthCheckEndpointResponse.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_check_endpoint_post(connection, auth_set_check_endpoint_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/account/check-endpoint")
      |> add_param(:body, :body, auth_set_check_endpoint_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OddittApiClient.Model.AuthCheckEndpointResponse},
      {400, OddittApiClient.Model.AuthErrorResponse},
      {401, OddittApiClient.Model.AuthErrorResponse},
      {422, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  Get own client configuration

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_config_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_config_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/account/config")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {401, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  Create a new client secret

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthCreateSecretResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_secret_post(Tesla.Env.client, keyword()) :: {:ok, OddittApiClient.Model.AuthCreateSecretResponse.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_secret_post(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/account/secret")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, OddittApiClient.Model.AuthCreateSecretResponse},
      {401, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  List own client secrets

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthListSecretsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_secrets_get(Tesla.Env.client, keyword()) :: {:ok, OddittApiClient.Model.AuthListSecretsResponse.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_secrets_get(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/account/secrets")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OddittApiClient.Model.AuthListSecretsResponse},
      {401, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  Delete a client secret

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `secret_code` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_secrets_secret_code_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, OddittApiClient.Model.V1AccountApiKeysKeyCodeDelete409Response.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_secrets_secret_code_delete(connection, secret_code, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/v1/account/secrets/#{secret_code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {401, OddittApiClient.Model.AuthErrorResponse},
      {409, OddittApiClient.Model.V1AccountApiKeysKeyCodeDelete409Response}
    ])
  end

  @doc """
  Get own usage stats

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:start_date` (DateTime.t): 
    - `:end_date` (DateTime.t): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_account_usage_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_account_usage_get(connection, opts \\ []) do
    optional_params = %{
      :start_date => :query,
      :end_date => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/account/usage")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {401, OddittApiClient.Model.AuthErrorResponse}
    ])
  end
end
