# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Api.Authentication do
  @moduledoc """
  API calls for all endpoints tagged `Authentication`.
  """

  alias OddittApiClient.Connection
  import OddittApiClient.RequestBuilder

  @doc """
  Login with API key

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `x_api_key` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthTokenPair.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_auth_login_post(Tesla.Env.client, String.t, keyword()) :: {:ok, OddittApiClient.Model.AuthTokenPair.t} | {:error, Tesla.Env.t}
  def v1_auth_login_post(connection, x_api_key, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/auth/login")
      |> add_param(:headers, :"X-API-Key", x_api_key)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OddittApiClient.Model.AuthTokenPair}
    ])
  end

  @doc """
  Refresh tokens

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `auth_refresh_request` (AuthRefreshRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthTokenPair.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_auth_refresh_post(Tesla.Env.client, OddittApiClient.Model.AuthRefreshRequest.t, keyword()) :: {:ok, OddittApiClient.Model.AuthTokenPair.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_auth_refresh_post(connection, auth_refresh_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/auth/refresh")
      |> add_param(:body, :body, auth_refresh_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OddittApiClient.Model.AuthTokenPair},
      {400, OddittApiClient.Model.AuthErrorResponse},
      {422, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  OAuth login (client credentials)

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `auth_o_auth_login_request` (AuthOAuthLoginRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthTokenPair.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_oauth_login_post(Tesla.Env.client, OddittApiClient.Model.AuthOAuthLoginRequest.t, keyword()) :: {:ok, OddittApiClient.Model.AuthTokenPair.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_oauth_login_post(connection, auth_o_auth_login_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/oauth/login")
      |> add_param(:body, :body, auth_o_auth_login_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OddittApiClient.Model.AuthTokenPair},
      {400, OddittApiClient.Model.AuthErrorResponse},
      {401, OddittApiClient.Model.AuthErrorResponse},
      {422, OddittApiClient.Model.AuthErrorResponse}
    ])
  end

  @doc """
  OAuth refresh

  ### Parameters

  - `connection` (OddittApiClient.Connection): Connection to server
  - `auth_refresh_request` (AuthRefreshRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OddittApiClient.Model.AuthTokenPair.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_oauth_refresh_post(Tesla.Env.client, OddittApiClient.Model.AuthRefreshRequest.t, keyword()) :: {:ok, OddittApiClient.Model.AuthTokenPair.t} | {:ok, OddittApiClient.Model.AuthErrorResponse.t} | {:error, Tesla.Env.t}
  def v1_oauth_refresh_post(connection, auth_refresh_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/oauth/refresh")
      |> add_param(:body, :body, auth_refresh_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, OddittApiClient.Model.AuthTokenPair},
      {400, OddittApiClient.Model.AuthErrorResponse},
      {422, OddittApiClient.Model.AuthErrorResponse}
    ])
  end
end
