# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1AffiliatesEventsPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :country_code,
    :device_type,
    :event_type,
    :offer_campaign,
    :offer_id,
    :offer_label,
    :operator_id,
    :session_token,
    :subnational_region_code
  ]

  @type t :: %__MODULE__{
    :country_code => String.t,
    :device_type => String.t | nil,
    :event_type => String.t,
    :offer_campaign => String.t | nil,
    :offer_id => String.t,
    :offer_label => String.t | nil,
    :operator_id => integer(),
    :session_token => String.t | nil,
    :subnational_region_code => String.t | nil
  }

  def decode(value) do
    value
  end
end

