# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1AccountApiKeysKeyCodeDelete409Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :error,
    :success
  ]

  @type t :: %__MODULE__{
    :error => String.t,
    :success => boolean()
  }

  def decode(value) do
    value
  end
end

