# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1TrendsFlowsByIdPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :fact_flow_type,
    :flow_ids,
    :flow_type,
    :use_cartoon_images
  ]

  @type t :: %__MODULE__{
    :fact_flow_type => String.t | nil,
    :flow_ids => [integer()],
    :flow_type => String.t,
    :use_cartoon_images => boolean() | nil
  }

  def decode(value) do
    value
  end
end

