# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1AffiliatesEventPositionPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :country_code,
    :event_betting_market_position_id,
    :hide_offers_links,
    :odds_format,
    :offer_campaign,
    :operator_ids,
    :operator_keys,
    :product_mode,
    :subnational_region_code,
    :use_cartoon_images
  ]

  @type t :: %__MODULE__{
    :country_code => String.t | nil,
    :event_betting_market_position_id => integer(),
    :hide_offers_links => boolean() | nil,
    :odds_format => String.t | nil,
    :offer_campaign => String.t | nil,
    :operator_ids => [integer()] | nil,
    :operator_keys => [String.t] | nil,
    :product_mode => String.t | nil,
    :subnational_region_code => String.t | nil,
    :use_cartoon_images => boolean() | nil
  }

  def decode(value) do
    value
  end
end

