# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1EventsUpcomingEventsPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :event_date,
    :league_id,
    :league_key,
    :page,
    :page_size,
    :sport_id,
    :sport_key,
    :timezone
  ]

  @type t :: %__MODULE__{
    :event_date => Date.t | nil,
    :league_id => integer() | nil,
    :league_key => String.t | nil,
    :page => integer() | nil,
    :page_size => integer() | nil,
    :sport_id => integer() | nil,
    :sport_key => String.t | nil,
    :timezone => String.t | nil
  }

  def decode(value) do
    value
  end
end

