# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1OddsUpcomingOddsByEventPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :event_id,
    :operator_ids,
    :page,
    :page_size
  ]

  @type t :: %__MODULE__{
    :event_id => integer(),
    :operator_ids => [integer()] | nil,
    :page => integer() | nil,
    :page_size => integer() | nil
  }

  def decode(value) do
    value
  end
end

