# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1AffiliatesLinksBulkPatchRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :filter,
    :patch
  ]

  @type t :: %__MODULE__{
    :filter => map(),
    :patch => map()
  }

  def decode(value) do
    value
  end
end

