# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1AffiliatesLinksBulkPost202Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :job_id,
    :mode,
    :poll_url,
    :status,
    :submitted_rows
  ]

  @type t :: %__MODULE__{
    :job_id => String.t | nil,
    :mode => String.t | nil,
    :poll_url => String.t | nil,
    :status => String.t | nil,
    :submitted_rows => integer() | nil
  }

  def decode(value) do
    value
  end
end

