# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1AffiliatesLinksPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :android_deep_link_url,
    :country_code,
    :ios_deep_link_url,
    :is_active,
    :offer_call_to_action,
    :offer_campaign,
    :offer_category_id,
    :offer_display_bullets,
    :offer_display_small_print,
    :offer_ev_usd,
    :offer_label,
    :offer_priority,
    :offer_tagline,
    :operator_id,
    :operator_name,
    :source_network_affiliate_partner_id,
    :subnational_region_code,
    :web_deep_link_url
  ]

  @type t :: %__MODULE__{
    :android_deep_link_url => Uri | nil,
    :country_code => String.t | nil,
    :ios_deep_link_url => Uri | nil,
    :is_active => boolean() | nil,
    :offer_call_to_action => String.t | nil,
    :offer_campaign => String.t | nil,
    :offer_category_id => integer(),
    :offer_display_bullets => [String.t] | nil,
    :offer_display_small_print => String.t | nil,
    :offer_ev_usd => number() | nil,
    :offer_label => String.t | nil,
    :offer_priority => integer() | nil,
    :offer_tagline => String.t | nil,
    :operator_id => integer() | nil,
    :operator_name => String.t | nil,
    :source_network_affiliate_partner_id => integer() | nil,
    :subnational_region_code => String.t | nil,
    :web_deep_link_url => Uri
  }

  alias OddittApiClient.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:android_deep_link_url, :struct, OddittApiClient.Model.Uri)
     |> Deserializer.deserialize(:ios_deep_link_url, :struct, OddittApiClient.Model.Uri)
     |> Deserializer.deserialize(:web_deep_link_url, :struct, OddittApiClient.Model.Uri)
  end
end

