# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1TrendsFlowsPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :bet_type,
    :betting_market_category_id,
    :betting_market_category_ids,
    :betting_market_entity_type,
    :betting_market_ids,
    :betting_market_position_id,
    :betting_market_position_ids,
    :event_id,
    :event_ids,
    :event_start_date_from,
    :event_start_date_to,
    :fact_flow_type,
    :flow_type,
    :focus_entity_type_id,
    :full_hit_rate,
    :include_alt_lines,
    :include_deeplinks,
    :include_only_basic_trends,
    :include_star_sign_content,
    :league_id,
    :league_ids,
    :league_key,
    :likelihood_type,
    :max_hit_rate_threshold,
    :max_implied_probability_threshold,
    :min_hit_rate_threshold,
    :min_implied_probability_threshold,
    :odds_format,
    :operator_ids,
    :operator_keys,
    :page,
    :page_size,
    :player_id,
    :player_ids,
    :player_key,
    :product_mode,
    :split_type,
    :sport_id,
    :sport_ids,
    :sport_key,
    :starting_soon,
    :team_id,
    :team_ids,
    :team_key,
    :team_split,
    :use_cartoon_images
  ]

  @type t :: %__MODULE__{
    :bet_type => String.t | nil,
    :betting_market_category_id => integer() | nil,
    :betting_market_category_ids => [integer()] | nil,
    :betting_market_entity_type => String.t | nil,
    :betting_market_ids => [integer()] | nil,
    :betting_market_position_id => integer() | nil,
    :betting_market_position_ids => [integer()] | nil,
    :event_id => integer() | nil,
    :event_ids => [integer()] | nil,
    :event_start_date_from => DateTime.t | nil,
    :event_start_date_to => DateTime.t | nil,
    :fact_flow_type => String.t | nil,
    :flow_type => String.t | nil,
    :focus_entity_type_id => integer() | nil,
    :full_hit_rate => boolean() | nil,
    :include_alt_lines => boolean() | nil,
    :include_deeplinks => boolean() | nil,
    :include_only_basic_trends => boolean() | nil,
    :include_star_sign_content => boolean() | nil,
    :league_id => integer() | nil,
    :league_ids => [integer()] | nil,
    :league_key => String.t | nil,
    :likelihood_type => String.t | nil,
    :max_hit_rate_threshold => integer() | nil,
    :max_implied_probability_threshold => float() | nil,
    :min_hit_rate_threshold => integer() | nil,
    :min_implied_probability_threshold => float() | nil,
    :odds_format => String.t | nil,
    :operator_ids => [integer()] | nil,
    :operator_keys => [String.t] | nil,
    :page => integer() | nil,
    :page_size => integer() | nil,
    :player_id => integer() | nil,
    :player_ids => [integer()] | nil,
    :player_key => String.t | nil,
    :product_mode => String.t | nil,
    :split_type => String.t | nil,
    :sport_id => integer() | nil,
    :sport_ids => [integer()] | nil,
    :sport_key => String.t | nil,
    :starting_soon => boolean() | nil,
    :team_id => integer() | nil,
    :team_ids => [integer()] | nil,
    :team_key => String.t | nil,
    :team_split => String.t | nil,
    :use_cartoon_images => boolean() | nil
  }

  def decode(value) do
    value
  end
end

