# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1ReferencesTagDimensionsGet200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :records
  ]

  @type t :: %__MODULE__{
    :records => [map()] | nil
  }

  def decode(value) do
    value
  end
end

