# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.V1TrendsByBettingMarketPositionPostRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :event_betting_market_position_ids,
    :odds_format,
    :product_mode,
    :use_cartoon_images
  ]

  @type t :: %__MODULE__{
    :event_betting_market_position_ids => [integer()],
    :odds_format => String.t | nil,
    :product_mode => String.t | nil,
    :use_cartoon_images => boolean() | nil
  }

  def decode(value) do
    value
  end
end

