# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AffiliateErrorResponseError do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :message
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :message => String.t
  }

  def decode(value) do
    value
  end
end

