# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthRefreshRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :refresh_token
  ]

  @type t :: %__MODULE__{
    :refresh_token => String.t
  }

  def decode(value) do
    value
  end
end

