# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthCheckEndpointResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :success
  ]

  @type t :: %__MODULE__{
    :data => OddittApiClient.Model.AuthCheckEndpointResponseData.t | nil,
    :success => boolean() | nil
  }

  alias OddittApiClient.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :struct, OddittApiClient.Model.AuthCheckEndpointResponseData)
  end
end

