# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthSetCheckEndpointRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :allow_multiple,
    :auth_header_name,
    :auth_scheme,
    :auth_token,
    :method,
    :url
  ]

  @type t :: %__MODULE__{
    :allow_multiple => boolean() | nil,
    :auth_header_name => String.t | nil,
    :auth_scheme => String.t | nil,
    :auth_token => String.t,
    :method => String.t,
    :url => Uri
  }

  alias OddittApiClient.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:url, :struct, OddittApiClient.Model.Uri)
  end
end

