# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthListSecretsResponseSecretsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :created_at,
    :secret_code,
    :secret_preview,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t | nil,
    :secret_code => String.t | nil,
    :secret_preview => String.t | nil,
    :updated_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

