# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthCreateSecretResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :client_secret
  ]

  @type t :: %__MODULE__{
    :client_secret => String.t | nil
  }

  def decode(value) do
    value
  end
end

