# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthCreateApiKeyResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :api_key,
    :key_code,
    :message,
    :success
  ]

  @type t :: %__MODULE__{
    :api_key => String.t | nil,
    :key_code => String.t | nil,
    :message => String.t | nil,
    :success => boolean() | nil
  }

  def decode(value) do
    value
  end
end

