# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthTokenPair do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :access_token,
    :expires_at,
    :expires_in,
    :refresh_token,
    :token_type
  ]

  @type t :: %__MODULE__{
    :access_token => String.t,
    :expires_at => DateTime.t,
    :expires_in => integer(),
    :refresh_token => String.t,
    :token_type => String.t
  }

  def decode(value) do
    value
  end
end

