# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthListApiKeysResponseApiKeysInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :active,
    :created_at,
    :expires_at,
    :key_code,
    :name,
    :widget
  ]

  @type t :: %__MODULE__{
    :active => boolean() | nil,
    :created_at => DateTime.t | nil,
    :expires_at => DateTime.t | nil,
    :key_code => String.t | nil,
    :name => String.t | nil,
    :widget => boolean() | nil
  }

  def decode(value) do
    value
  end
end

