# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthErrorResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
    :error => OddittApiClient.Model.AffiliateErrorResponseError.t
  }

  alias OddittApiClient.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:error, :struct, OddittApiClient.Model.AffiliateErrorResponseError)
  end
end

