# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthListSecretsResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :secrets,
    :success
  ]

  @type t :: %__MODULE__{
    :secrets => [OddittApiClient.Model.AuthListSecretsResponseSecretsInner.t] | nil,
    :success => boolean() | nil
  }

  alias OddittApiClient.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:secrets, :list, OddittApiClient.Model.AuthListSecretsResponseSecretsInner)
  end
end

