# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.AuthListApiKeysResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :api_keys,
    :success
  ]

  @type t :: %__MODULE__{
    :api_keys => [OddittApiClient.Model.AuthListApiKeysResponseApiKeysInner.t] | nil,
    :success => boolean() | nil
  }

  alias OddittApiClient.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:api_keys, :list, OddittApiClient.Model.AuthListApiKeysResponseApiKeysInner)
  end
end

