# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.TrendsQuoteFlowItem do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :country,
    :event_betting_market_position_ids,
    :flow_id,
    :flow_type,
    :region
  ]

  @type t :: %__MODULE__{
    :country => String.t,
    :event_betting_market_position_ids => [integer()],
    :flow_id => integer(),
    :flow_type => String.t,
    :region => String.t | nil
  }

  def decode(value) do
    value
  end
end

