# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.TrendsQuoteSandboxResponse do
  @moduledoc """
  Mock pricing response. Shape differs between single (1-leg) and parlay (2+ legs); parlay responses additionally carry top-level combined odds and is_combinable / parlay_failure_reason.
  """

  @derive JSON.Encoder
  defstruct [
    :american_odds_value,
    :button_payload,
    :decimal_odds_value,
    :event_betting_market_position_maps,
    :flow_id,
    :flow_type,
    :fractional_odds_value,
    :is_combinable,
    :odds_implied_probability,
    :parlay_failure_reason,
    :payout_multiplier
  ]

  @type t :: %__MODULE__{
    :american_odds_value => String.t | nil,
    :button_payload => String.t | nil,
    :decimal_odds_value => number() | nil,
    :event_betting_market_position_maps => [map()],
    :flow_id => integer(),
    :flow_type => String.t,
    :fractional_odds_value => String.t | nil,
    :is_combinable => boolean() | nil,
    :odds_implied_probability => number() | nil,
    :parlay_failure_reason => String.t | nil,
    :payout_multiplier => number() | nil
  }

  def decode(value) do
    value
  end
end

