# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.TrendsQuoteSandboxRequest do
  @moduledoc """
  Single hydrated pricing payload — the exact shape /v1/trends/flows/quote sends in each outbound call. Wire this endpoint into /v1/account/check-endpoint to round-trip the widget call entirely on platform infrastructure (no real operator needed).
  """

  @derive JSON.Encoder
  defstruct [
    :country,
    :event_betting_market_position_maps,
    :flow_id,
    :flow_type,
    :region
  ]

  @type t :: %__MODULE__{
    :country => String.t,
    :event_betting_market_position_maps => [map()],
    :flow_id => integer(),
    :flow_type => String.t,
    :region => String.t | nil
  }

  def decode(value) do
    value
  end
end

