# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.TrendsPaginatedResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :page,
    :page_size,
    :records,
    :total_count,
    :total_pages
  ]

  @type t :: %__MODULE__{
    :page => integer() | nil,
    :page_size => integer() | nil,
    :records => [map()] | nil,
    :total_count => integer() | nil,
    :total_pages => integer() | nil
  }

  def decode(value) do
    value
  end
end

