# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OddittApiClient.Model.TrendsWidgetEventRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :event_body,
    :event_type,
    :mode
  ]

  @type t :: %__MODULE__{
    :event_body => %{optional(String.t) => any()},
    :event_type => String.t,
    :mode => String.t | nil
  }

  def decode(value) do
    value
  end
end

